let array=[2,5,7,9,4,8]

array.forEach(a=> console.log(a) )      //forEach



/*
    STEP 01

let Elements=[2,5,7,9,4,8]
function Demo(a)
    {
    console.log(a)
    }
Elements.forEach(Demo)

       STEP 02 -- Anonymous function

let Elements=[2,5,7,9,4,8]
let Demo1=function (a)
    {
    console.log(a)
    }
Elements.forEach(Demo1)

       STEP 03 -- Arrow function

let Elements=[2,5,7,9,4,8]
let Demo1= a=> console.log(a)
Elements.forEach(Demo1)

       STEP 04 -- ForEach

let Elements=[2,5,7,9,4,8]
Elements.forEach(a=> console.log(a) )

*/


